### ISSUE TITLE
Inquiry about Data Source about the landslide inventory

### ISSUE THREAD

**Issue by keepfighting666** [kushanavbhuyan/Large-scale-multi-spatiotemporal-landslide-mapping#3]
Could you please provide me with more details about the data source? Knowing the origin and any relevant documentation would greatly assist me in understanding and using the data effectively for my research.

Thank you in advance for your assistance.

**Comment by kushanavbhuyan** [comment]
The data regarding the inventories were accessed via landslide inventories published in the literature. I will share their links below.

The data regarding the satellite imagery was downloaded from PlanetLabs, and the images are a combination of the PlanetScope and RapidEye images.

Links: 

https://www.frontiersin.org/articles/10.3389/feart.2021.700546/full
https://link.springer.com/article/10.1007/s10346-022-01869-9
https://essd.copernicus.org/articles/11/35/2019/
https://www.mdpi.com/2076-3263/9/10/437
